//const express = require('express');
var deleteSnack = require('../controllers/snack.js').deleteSnack;
//const { requiresAuth } = require('express-openid-connect');
//const router = express.Router();
router.get('/', requiresAuth(), function (req, res) { return res.json("got all"); });
router.get('/:id', requiresAuth(), function (req, res) { return res.json("got snack"); });
router.get('/random', requiresAuth(), function (req, res) { return res.json("got random"); });
router.post('/', requiresAuth(), function (req, res) { return res.json("inserted that"); });
router.put('/', requiresAuth(), function (req, res) { return res.json("edited that"); });
router.delete('/', requiresAuth(), deleteSnack);
module.exports = router;
