PUT http://localhost:3001/snack/64a774f844c77327a1c977e8 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiSnVzdGluIiwiZmFtaWx5X25hbWUiOiJCZW5jaCIsIm5pY2tuYW1lIjoianVzdGluLmQuYmVuY2giLCJuYW1lIjoiSnVzdGluIEJlbmNoIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FBY0hUdGY3SUJEZW9XdFJDcUpmV0ktV0hsNVZyRmJpMkp0MmNjQThpMm5YbG1mWmRSRXo9czk2LWMiLCJsb2NhbGUiOiJlbiIsInVwZGF0ZWRfYXQiOiIyMDIzLTA3LTEyVDIyOjEyOjEyLjkyNloiLCJlbWFpbCI6Imp1c3Rpbi5kLmJlbmNoQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczovL2t1YnV0b2RyaXAudXMuYXV0aDAuY29tLyIsImF1ZCI6Im9rcXp0dUVuczVraEhnY1R3UmlPazZxT3F0MmRRekJjIiwiaWF0IjoxNjg5MjAwMzE1LCJleHAiOjE2ODkyMzYzMTUsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTA0Mzk4ODExODQ5ODQyOTc2Mzc5Iiwic2lkIjoiSkg4bF9kTmp0NmhWVDJLb2cyS0tlSlhuai1tckRZX0UiLCJub25jZSI6ImMtSlN2RnhqdTVtOU5KNUQyRllReGZNTUZtaWIyVThPZDNEX3BiNmFQMWMifQ.geNmXQhj4AtCrTM_NJVPIbeiI-8W1STH6Zjc9Hz82aA

{
  "type": "snack",
  "maker": "Taco Johns",
  "name": "any",
  "ounces": "any",
  "calories": "any",
  "sugar": "any",
  "totalFat": "any",
  "ingredients": "stuff"
}
###
DELETE  http://localhost:3001/snack/snack/64a774f844c77327a1c977e8 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiSnVzdGluIiwiZmFtaWx5X25hbWUiOiJCZW5jaCIsIm5pY2tuYW1lIjoianVzdGluLmQuYmVuY2giLCJuYW1lIjoiSnVzdGluIEJlbmNoIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FBY0hUdGY3SUJEZW9XdFJDcUpmV0ktV0hsNVZyRmJpMkp0MmNjQThpMm5YbG1mWmRSRXo9czk2LWMiLCJsb2NhbGUiOiJlbiIsInVwZGF0ZWRfYXQiOiIyMDIzLTA3LTEyVDIyOjEyOjEyLjkyNloiLCJlbWFpbCI6Imp1c3Rpbi5kLmJlbmNoQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczovL2t1YnV0b2RyaXAudXMuYXV0aDAuY29tLyIsImF1ZCI6Im9rcXp0dUVuczVraEhnY1R3UmlPazZxT3F0MmRRekJjIiwiaWF0IjoxNjg5MjAwMzE1LCJleHAiOjE2ODkyMzYzMTUsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTA0Mzk4ODExODQ5ODQyOTc2Mzc5Iiwic2lkIjoiSkg4bF9kTmp0NmhWVDJLb2cyS0tlSlhuai1tckRZX0UiLCJub25jZSI6ImMtSlN2RnhqdTVtOU5KNUQyRllReGZNTUZtaWIyVThPZDNEX3BiNmFQMWMifQ.geNmXQhj4AtCrTM_NJVPIbeiI-8W1STH6Zjc9Hz82aA
###
PUT https://kabutodrip.onrender.com/snack/64a772ee28634b65097f2055 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiSnVzdGluIiwiZmFtaWx5X25hbWUiOiJCZW5jaCIsIm5pY2tuYW1lIjoianVzdGluLmQuYmVuY2giLCJuYW1lIjoiSnVzdGluIEJlbmNoIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FBY0hUdGY3SUJEZW9XdFJDcUpmV0ktV0hsNVZyRmJpMkp0MmNjQThpMm5YbG1mWmRSRXo9czk2LWMiLCJsb2NhbGUiOiJlbiIsInVwZGF0ZWRfYXQiOiIyMDIzLTA3LTEyVDIyOjEyOjEyLjkyNloiLCJlbWFpbCI6Imp1c3Rpbi5kLmJlbmNoQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczovL2t1YnV0b2RyaXAudXMuYXV0aDAuY29tLyIsImF1ZCI6Im9rcXp0dUVuczVraEhnY1R3UmlPazZxT3F0MmRRekJjIiwiaWF0IjoxNjg5MjAwMzE1LCJleHAiOjE2ODkyMzYzMTUsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTA0Mzk4ODExODQ5ODQyOTc2Mzc5Iiwic2lkIjoiSkg4bF9kTmp0NmhWVDJLb2cyS0tlSlhuai1tckRZX0UiLCJub25jZSI6ImMtSlN2RnhqdTVtOU5KNUQyRllReGZNTUZtaWIyVThPZDNEX3BiNmFQMWMifQ.geNmXQhj4AtCrTM_NJVPIbeiI-8W1STH6Zjc9Hz82aA

{
  "type": "snack",
  "maker": "any",
  "name": "any",
  "ounces": "any",
  "calories": "any",
  "sugar": "any",
  "totalFat": "any",
  "ingredients": "any"
}
###
DELETE https://kabutodrip.onrender.com/snack/snack/64a772ee28634b65097f2055 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnaXZlbl9uYW1lIjoiSnVzdGluIiwiZmFtaWx5X25hbWUiOiJCZW5jaCIsIm5pY2tuYW1lIjoianVzdGluLmQuYmVuY2giLCJuYW1lIjoiSnVzdGluIEJlbmNoIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FBY0hUdGY3SUJEZW9XdFJDcUpmV0ktV0hsNVZyRmJpMkp0MmNjQThpMm5YbG1mWmRSRXo9czk2LWMiLCJsb2NhbGUiOiJlbiIsInVwZGF0ZWRfYXQiOiIyMDIzLTA3LTEyVDIyOjEyOjEyLjkyNloiLCJlbWFpbCI6Imp1c3Rpbi5kLmJlbmNoQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJpc3MiOiJodHRwczovL2t1YnV0b2RyaXAudXMuYXV0aDAuY29tLyIsImF1ZCI6Im9rcXp0dUVuczVraEhnY1R3UmlPazZxT3F0MmRRekJjIiwiaWF0IjoxNjg5MjAwMzE1LCJleHAiOjE2ODkyMzYzMTUsInN1YiI6Imdvb2dsZS1vYXV0aDJ8MTA0Mzk4ODExODQ5ODQyOTc2Mzc5Iiwic2lkIjoiSkg4bF9kTmp0NmhWVDJLb2cyS0tlSlhuai1tckRZX0UiLCJub25jZSI6ImMtSlN2RnhqdTVtOU5KNUQyRllReGZNTUZtaWIyVThPZDNEX3BiNmFQMWMifQ.geNmXQhj4AtCrTM_NJVPIbeiI-8W1STH6Zjc9Hz82aA
###
GET http://localhost:3001/Snack/getAllCandyPastries