###
GET http://localhost:3001/SampleData1
###
POST http://localhost:3001/SampleData1 HTTP/1.1
Content-Type: application/json

{
    "item1": "plant",
    "item2": "pot",
    "item3": "water",
    "item4": "soil"
}
###
GET http://localhost:3001/SampleData2
###
POST http://localhost:3001/SampleData2 HTTP/1.1
Content-Type: application/json

{
    "item1": "dog",
    "item2": "cat",
    "item3": "bird",
    "item4": "snake"
}
###
PUT http://localhost:3001/SampleData1/646bfe99c2cb5f9baecdcada HTTP/1.1
content-type: application/json
{
    "item1": "lemonade",
    "item2": "rootbeer",
    "item3": "cola",
    "item4": "milk"
}
###
DELETE  http://localhost:3001/SampleData1/646bfe99c2cb5f9baecdcada HTTP/1.1
###
PUT http://localhost:3001/SampleData2/64697cbc7f006d51681c2ffc HTTP/1.1
content-type: application/json
{
    "item1": "nintendo",
    "item2": "microsoft",
    "item3": "sony",
    "item4": "valve"
}
###
DELETE  http://localhost:3001/SampleData2/64697cbc7f006d51681c2ffc HTTP/1.1
###









###
GET https://cse341-cbjm.onrender.com/SampleData1
###
POST https://cse341-cbjm.onrender.com/SampleData1 HTTP/1.1
Content-Type: application/json

{
    "item1": "plant",
    "item2": "pot",
    "item3": "water",
    "item4": "soil"
}
###
GET https://cse341-cbjm.onrender.com/SampleData2
###
POST https://cse341-cbjm.onrender.com/SampleData2 HTTP/1.1
Content-Type: application/json

{
    "item1": "dog",
    "item2": "cat",
    "item3": "bird",
    "item4": "snake",
    "item5": "bear",
    "item6": "duck",
    "item7": "chicken"
}

###
PUT https://cse341-cbjm.onrender.com/SampleData1/646bfe99c2cb5f9baecdcada HTTP/1.1
content-type: application/json
{
    "item1": "lemonade",
    "item2": "rootbeer",
    "item3": "cola",
    "item4": "milk"
}
###
DELETE  https://cse341-cbjm.onrender.com/SampleData1/646bfe99c2cb5f9baecdcada HTTP/1.1
###
PUT https://cse341-cbjm.onrender.com/SampleData2/64697cbc7f006d51681c2ffc HTTP/1.1
content-type: application/json
{
    "item1": "nintendo",
    "item2": "microsoft",
    "item3": "sony",
    "item4": "valve",
    "item5": "ubisoft",
    "item6": "bungie",
    "item7": "wotc"
}
###
DELETE  https://cse341-cbjm.onrender.com/SampleData2/64697cbc7f006d51681c2ffc HTTP/1.1
###